import { useEffect, useState } from 'react'
import './App.css'

const numbers = Array.from({ length: 30 }, (_, i) => i + 1)
const reserved = new Set([4, 7, 12, 18, 23])
const confirmed = new Set([2, 9, 15, 26])
const pad = n => String(n).padStart(2, '0')
const Logo = () => <a className="brand" href="/">mimo<span>.</span></a>

function PublicRaffle() {
  const [selected, setSelected] = useState(null)
  const [formOpen, setFormOpen] = useState(false)
  const [done, setDone] = useState(false)
  const [name, setName] = useState('')
  const state = n => confirmed.has(n) ? 'confirmed' : reserved.has(n) ? 'reserved' : selected === n ? 'selected' : ''
  return <main>
    <section className="hero"><nav className="nav content"><Logo/><div className="nav-links"><a href="#como-funciona">Como funciona</a><a className="admin-link" href="/admin">Área do organizador</a></div></nav><div className="content hero-content"><p className="eyebrow">CHÁ DE BEBÊ DA MALU</p><h1>Um número, um carinho<br/>para a nossa pequena.</h1><p className="hero-copy">Escolha seu número da sorte e nos ajude a preparar cada detalhe da chegada da Malu.</p><a className="primary-button" href="#numeros">Escolher meu número <span>↓</span></a></div><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/></section>
    <section className="content event-card"><div className="event-date"><strong>28</strong><span>SET<br/>2026</span></div><div><p className="card-label">SORTEIO</p><h2>R$ 500,00 via Pix</h2><p>O sorteio será realizado on-line e divulgado para todos.</p></div><div className="divider"/><div><p className="card-label">PARTICIPAÇÃO</p><h2>Fraldas ou Pix</h2><p>Você escolhe como prefere participar.</p></div></section>
    <section className="content raffle" id="numeros"><div className="section-heading"><div><p className="eyebrow">ESCOLHA UM NÚMERO</p><h2>A sua sorte pode fazer parte dessa história.</h2></div><div className="legend"><span><i className="dot available"/>Disponível</span><span><i className="dot reserved-dot"/>Reservado</span><span><i className="dot confirmed-dot"/>Confirmado</span></div></div><div className="number-grid">{numbers.map(n=><button key={n} className={`number ${state(n)}`} disabled={reserved.has(n)||confirmed.has(n)} onClick={()=>setSelected(n)}>{pad(n)}</button>)}</div><div className="selection-box"><div><p className="card-label">SEU NÚMERO</p><strong>{selected?pad(selected):'—'}</strong></div><p>{selected?'Perfeito! Continue para informar seus dados e a forma de participação.':'Toque em um número disponível para continuar.'}</p><button className="continue" disabled={!selected} onClick={()=>setFormOpen(true)}>Continuar <span>→</span></button></div></section>
    <section className="how" id="como-funciona"><div className="content how-layout"><div><p className="eyebrow">É SIMPLES PARTICIPAR</p><h2>Seu gesto vai encher o enxoval de amor.</h2></div><ol><li><span>01</span><div><h3>Escolha seu número</h3><p>Selecione um número disponível na rifa.</p></div></li><li><span>02</span><div><h3>Conte como vai participar</h3><p>Escolha fraldas, Pix ou os dois e preencha seus dados.</p></div></li><li><span>03</span><div><h3>Pronto, você está dentro!</h3><p>Receba a confirmação e participe do sorteio.</p></div></li></ol></div></section><footer><div className="content"><Logo/><p>Feito com carinho para celebrar a chegada da Malu.</p></div></footer>
    {formOpen&&<div className="modal"><form onSubmit={e=>{e.preventDefault();setFormOpen(false);setDone(true)}}><button type="button" className="close" onClick={()=>setFormOpen(false)}>×</button><p className="eyebrow">NÚMERO {pad(selected)}</p><h2>Vamos confirmar sua participação?</h2><p className="form-copy">Você receberá as instruções pelo WhatsApp.</p><label>Seu nome<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Como podemos te chamar?"/></label><label>WhatsApp<input required placeholder="(00) 00000-0000"/></label><div className="form-row"><label>Tamanho<select><option>M</option><option>P</option><option>G</option><option>XG</option></select></label><label>Pacotes<select><option>1</option><option>2</option><option>3</option></select></label></div><label>Marca da fralda<input placeholder="Ex.: Pampers, Huggies..."/></label><button className="continue submit">Confirmar participação →</button></form></div>}
    {done&&<div className="modal"><div className="success"><b>✓</b><p className="eyebrow">TUDO CERTO</p><h2>Que alegria ter você com a gente!</h2><p>O número <strong>{pad(selected)}</strong> está reservado para <strong>{name}</strong>. Em breve enviaremos os próximos passos.</p><button className="continue submit" onClick={()=>setDone(false)}>Voltar para a rifa</button></div></div>}
  </main>
}

function Admin() {
 const [page,setPage]=useState('Visão geral'); const items=['Visão geral','Números','Participantes','Pagamentos','Fraldas','Sorteio']; const rows=[['Ana Luiza','09','M · Huggies','Confirmado'],['Marina Costa','15','G · Pampers','Confirmado'],['Paulo Henrique','04','Pix','Aguardando'],['Lívia Souza','23','P · Cremer','Reservado']]
 return <div className="admin-shell"><aside><Logo/><div className="event"><b>M</b><span><small>EVENTO ATIVO</small>Chá da Malu</span><i>⌄</i></div><nav>{items.map((x,i)=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}><i>{['◫','▦','♙','◌','▱','☆'][i]}</i>{x}</button>)}</nav><div className="aside-bottom"><a href="/">↗ Ver página pública</a><button>⚙ Configurações</button><p><b>RA</b><span>Rafael Almeida<small>Organizador</small></span></p></div></aside><main className="admin-main"><header><div><p>MEUS EVENTOS / CHÁ DA MALU</p><h1>{page}</h1></div><a href="/">Ver página pública ↗</a></header>{page==='Visão geral'?<div className="dash"><section className="banner"><div><small>CHÁ DE BEBÊ DA MALU</small><h2>Faltam <b>51 dias</b> para o sorteio.</h2><p>28 de setembro de 2026 · R$ 500,00 em prêmio</p></div><a href="/">Compartilhar link ↗</a></section><section className="metrics"><Card a="NÚMEROS CONFIRMADOS" b="18" c="de 30 números"/><Card a="VALOR ARRECADADO" b="R$ 270" c="R$ 30 pendentes"/><Card a="PACOTES DE FRALDAS" b="14" c="8 recebidos"/><Card a="PARTICIPANTES" b="22" c="4 aguardando ação"/></section><section className="twocol"><article><Head title="Andamento da rifa" text="Distribuição dos números"/><div className="progress"><p><span>60% preenchido</span><b>18 / 30</b></p><i><b/></i><small>● 18 confirmados　● 5 reservados　○ 7 disponíveis</small></div><div className="mini-grid">{numbers.map(n=><span className={confirmed.has(n)?'yes':reserved.has(n)?'wait':''} key={n}>{pad(n)}</span>)}</div></article><article><Head title="Fraldas por tamanho" text="Pacotes previstos"/><div className="bars">{[['P','21%',3],['M','43%',6],['G','29%',4],['XG','7%',1]].map(([a,b,c])=><p key={a}><span>{a}</span><i><b style={{width:b}}/></i><strong>{c}</strong></p>)}</div><div className="received">✓ <span><b>8 pacotes recebidos</b><br/>de 14 informados pelos participantes</span></div></article></section><article className="recent"><Head title="Participações recentes" text="Acompanhe as últimas atualizações"/>{rows.map(r=><div className="recent-row" key={r[0]}><span><b>{r[0].split(' ').map(x=>x[0]).join('')}</b>{r[0]}</span><em>{r[1]}</em><span>{r[2]}</span><i className={r[3]}>{r[3]}</i></div>)}</article></div>:<div className="empty"><b>⌁</b><h2>{page}</h2><p>Esta área está preparada para a próxima fase do MVP.</p></div>}</main></div>
}
function Card({a,b,c}){return <article><p>{a}</p><b>{b}</b><small>{c}</small></article>};function Head({title,text}){return <div className="head"><div><h3>{title}</h3><p>{text}</p></div><button>Ver detalhes →</button></div>}
function AdminGate(){const [ready,setReady]=useState(false),[error,setError]=useState(''),[form,setForm]=useState({username:'admin',password:''});useEffect(()=>{fetch('/api/auth/session/',{credentials:'include'}).then(r=>r.ok).then(setReady).catch(()=>setReady(false))},[]);if(ready)return <Admin/>;return <main className="login-page"><section><Logo/><div className="login-card"><p className="eyebrow">ÁREA RESTRITA</p><h1>Olá, organizador.</h1><p>Acesse o painel para acompanhar sua rifa.</p><form onSubmit={async e=>{e.preventDefault();setError('');const r=await fetch('/api/auth/login/',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(r.ok)setReady(true);else setError('Usuário ou senha inválidos.')}}><label>Usuário<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></label><label>Senha<input required type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Digite sua senha"/></label>{error&&<small className="login-error">{error}</small>}<button className="continue submit">Entrar no painel →</button></form></div><a href="/">← Voltar para a página pública</a></section></main>}
function App(){return location.pathname.startsWith('/admin')?<AdminGate/>:<PublicRaffle/>};export default App
